- hosts:
    - localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: nvim
      ansible.builtin.include_role:
        name: nvim
      tags: nvim

    - name: tmux
      ansible.builtin.include_role:
        name: tmux
      tags: tmux

    - name: ghostty
      ansible.builtin.include_role:
        name: ghostty
      tags: ghostty

    - name: python
      ansible.builtin.include_role:
        name: python
      tags: python

    - name: zsh
      ansible.builtin.include_role:
        name: zsh
      tags: zsh

    - name: bash
      ansible.builtin.include_role:
        name: bash
      tags: bash

    - name: postgres
      ansible.builtin.include_role:
        name: postgres
      tags: postgres
