- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "Psqlrc | Create symlink to role files directory"
  ansible.builtin.file:
    src: ".psqlrc"
    dest: "{{ ansible_user_dir }}/.psqlrc"
    state: link
    force: true
